// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagementSystem.Data;

#nullable disable

namespace UserManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721055832_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Sales",
                            Email = "nancy.davolio@company.com",
                            IsActive = true,
                            ManagerId = 2,
                            Name = "Nancy",
                            Surname = "Davolio"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Sales",
                            Email = "andrew.fuller@company.com",
                            IsActive = true,
                            Name = "Andrew",
                            Surname = "Fuller"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Sales",
                            Email = "janet.leverling@company.com",
                            IsActive = true,
                            ManagerId = 2,
                            Name = "Janet",
                            Surname = "Leverling"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Sales",
                            Email = "margaret.peacock@company.com",
                            IsActive = true,
                            ManagerId = 2,
                            Name = "Margaret",
                            Surname = "Peacock"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Sales",
                            Email = "steven.buchanan@company.com",
                            IsActive = true,
                            ManagerId = 2,
                            Name = "Steven",
                            Surname = "Buchanan"
                        },
                        new
                        {
                            Id = 6,
                            Department = "Sales",
                            Email = "michael.suyama@company.com",
                            IsActive = true,
                            ManagerId = 5,
                            Name = "Michael",
                            Surname = "Suyama"
                        },
                        new
                        {
                            Id = 7,
                            Department = "Sales",
                            Email = "robert.king@company.com",
                            IsActive = false,
                            ManagerId = 5,
                            Name = "Robert",
                            Surname = "King"
                        },
                        new
                        {
                            Id = 8,
                            Department = "Sales",
                            Email = "laura.callahan@company.com",
                            IsActive = true,
                            ManagerId = 2,
                            Name = "Laura",
                            Surname = "Callahan"
                        },
                        new
                        {
                            Id = 9,
                            Department = "Sales",
                            Email = "anne.dodsworth@company.com",
                            IsActive = false,
                            ManagerId = 5,
                            Name = "Anne",
                            Surname = "Dodsworth"
                        });
                });

            modelBuilder.Entity("UserManagementSystem.Models.User", b =>
                {
                    b.HasOne("UserManagementSystem.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });
#pragma warning restore 612, 618
        }
    }
}
